version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - app-network
  
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_CREATE_TOPICS: "bpm-topic:1:1"
    networks:
      - app-network

  process-service:
    image: process-service:v0.0.1
    depends_on:
      - kafka
    volumes:
      - ../archive:/app/archive
      - ../definitions:/app/definitions
      - ../instances:/app/instances
      - ../payloads:/app/payloads
      - ../test:/app/test
    networks:
    - app-network

  definition-service:
    image: definition-service:v0.0.1
    depends_on:
      - kafka
    volumes:
      - ../archive:/app/archive
      - ../definitions:/app/definitions
      - ../instances:/app/instances
      - ../payloads:/app/payloads
      - ../test:/app/test
    networks:
    - app-network
  frontend:
    image: frontend:0.0.7
    environment:
      - VITE_KEYCLOAK_URL=http://keycloak:8080
      - VITE_KEYCLOAK_REALM=uengine
      - VITE_KEYCLOAK_CLIENT_ID=uengine
    networks:
      - app-network

  keycloak:
    image: quay.io/keycloak/keycloak:18.0.1
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_LOGLEVEL: debug
      KC_METRICS_ENABLED: "true"
      KC_HTTP_ENABLED: "true"
      KC_PROXY: edge
      KC_SPI_THEME_DEFAULT: keycloak
      KC_SPI_THEME_WELCOME_THEME: keycloak
      KEYCLOAK_EXTRA_ARGS: "--spi-theme-static-max-age=-1 --spi-theme-cache-themes=false --spi-theme-cache-templates=false"
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    command: ["start-dev", "--import-realm"]
    networks:
      - app-network
  
  gateway:
    image: keycloak-gateway:0.0.5
    ports:
      - 8088:8080
    depends_on:
      - process-service
      - definition-service
      - frontend
      - keycloak
    environment:
      - KEYCLOAK_URI=http://keycloak:8080
      - KEYCLOAK_REALM=uengine
      - KEYCLOAK_CLIENT_ID=uengine
      - KEYCLOAK_CLIENT_SECRET=66LpF19OpkpgKKpWHdgiCEKisx5AXqLA
      - GATEWAY_URI=http://localhost:8088
      - SPRING_PROFILES_ACTIVE=docker
    restart: on-failure
    healthcheck:
      interval: 5s
      retries: 3
    networks:
      - app-network

volumes:
  archive:
  definitions:
  instances:
  payloads:
  test:
  
networks:
  app-network:
    driver: bridge

