-- ============================================================================
-- 예시: PAL_AP 전용 Private 시노님 (PAL_DB 오브젝트 참조)
-- ============================================================================
-- 전제    : 테이블/시퀀스는 PAL_DB에 있음. PAL_DB가 PAL_AP에 권한 부여 후
-- 실행    : PAL_AP 접속 후 이 스크립트 실행 (private 시노님은 자기 스키마에 생성)
-- 효과    : 앱이 PAL_AP로 접속 시 스키마 없이 TB_BPM_* 이름만으로 접근 가능. 코드 변경 없음.
-- ============================================================================

-- 시퀀스 (ID 생성용)
CREATE SYNONYM HIBERNATE_SEQUENCE FOR PAL_DB.HIBERNATE_SEQUENCE;

-- definition-service / process-service 공통
CREATE SYNONYM TB_BPM_PROCDEF     FOR PAL_DB.TB_BPM_PROCDEF;
CREATE SYNONYM TB_BPM_PDEF_VER    FOR PAL_DB.TB_BPM_PDEF_VER;
CREATE SYNONYM TB_BPM_DEF_INFO    FOR PAL_DB.TB_BPM_DEF_INFO;
CREATE SYNONYM TB_BPM_DEF_LOCK    FOR PAL_DB.TB_BPM_DEF_LOCK;
CREATE SYNONYM TB_BPM_PDEF_CMT    FOR PAL_DB.TB_BPM_PDEF_CMT;

-- process-service
CREATE SYNONYM TB_BPM_PROCINST    FOR PAL_DB.TB_BPM_PROCINST;
CREATE SYNONYM TB_BPM_WORKLIST    FOR PAL_DB.TB_BPM_WORKLIST;
CREATE SYNONYM TB_BPM_ROLEMAP     FOR PAL_DB.TB_BPM_ROLEMAP;
CREATE SYNONYM TB_BPM_AUDIT       FOR PAL_DB.TB_BPM_AUDIT;
CREATE SYNONYM TB_BPM_AUDIT_LOG   FOR PAL_DB.TB_BPM_AUDIT_LOG;
CREATE SYNONYM TB_BPM_EVTMAP      FOR PAL_DB.TB_BPM_EVTMAP;
CREATE SYNONYM TB_BPM_SERVICE     FOR PAL_DB.TB_BPM_SERVICE;
CREATE SYNONYM TB_BPM_SVC_EVT     FOR PAL_DB.TB_BPM_SVC_EVT;

-- ============================================================================
-- [참고] 권한 부여 예시 (PAL_DB 또는 DBA 접속 후 PAL_AP에게 실행)
-- ============================================================================
-- GRANT SELECT, INSERT, UPDATE, DELETE ON PAL_DB.HIBERNATE_SEQUENCE TO PAL_AP;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON PAL_DB.TB_BPM_PROCDEF    TO PAL_AP;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON PAL_DB.TB_BPM_PDEF_VER   TO PAL_AP;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON PAL_DB.TB_BPM_DEF_INFO   TO PAL_AP;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON PAL_DB.TB_BPM_DEF_LOCK   TO PAL_AP;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON PAL_DB.TB_BPM_PDEF_CMT   TO PAL_AP;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON PAL_DB.TB_BPM_PROCINST    TO PAL_AP;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON PAL_DB.TB_BPM_WORKLIST   TO PAL_AP;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON PAL_DB.TB_BPM_ROLEMAP    TO PAL_AP;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON PAL_DB.TB_BPM_AUDIT      TO PAL_AP;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON PAL_DB.TB_BPM_AUDIT_LOG   TO PAL_AP;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON PAL_DB.TB_BPM_EVTMAP      TO PAL_AP;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON PAL_DB.TB_BPM_SERVICE     TO PAL_AP;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON PAL_DB.TB_BPM_SVC_EVT     TO PAL_AP;
-- (시퀀스는 SELECT만으로는 부족할 수 있음. 필요 시 EXECUTE ON PAL_DB.HIBERNATE_SEQUENCE 등 적용)

EXIT;
