server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: execution
          uri: http://localhost:8000
          predicates:
            - Path=/complete/**, /vision-complete/**, /execution/**
          filters:
            - RewritePath=/execution/?(?<segment>.*), /$\{segment}
        - id: definition-service
          uri: http://localhost:9093
          predicates:
            - Path=/definition/**, /version/**, /versions/**
        - id: process-service
          uri: http://localhost:9094
          predicates:
            - Path=/worklist/**, /test/**, /instance/**, /work-item/** , /instances/**, /dry-run/**, /validate/**, /start-and-complete
        - id: frontend
          uri: http://localhost:5173
          predicates:
            - Path=/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: definition-service
          uri: http://definition-service:8080
          predicates:
            - Path=/definition/**, /version/**, /versions/**
        - id: process-service
          uri: http://process-service:8080
          predicates:
            - Path=/worklist/**, /test/**, /instance/**, /work-item/** , /instances/**, /dry-run/**, /validate/**, /start-and-complete
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080