version: '3.8'

services:  
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:18.0.1
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_LOGLEVEL: debug
      KC_METRICS_ENABLED: "true"
      KC_HTTP_ENABLED: "true"
      KC_PROXY: edge
      KC_SPI_THEME_DEFAULT: keycloak
      KC_SPI_THEME_WELCOME_THEME: keycloak
      KEYCLOAK_EXTRA_ARGS: "--spi-theme-static-max-age=-1 --spi-theme-cache-themes=false --spi-theme-cache-templates=false"
    command: ["start-dev"]
    # volumes:
    #   - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
    # command: ["start-dev", "--import-realm"]