server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
spring:
  application:
    name: definition

  main:
    allow-bean-definition-overriding: true
---
uengine:
  definition:
    basePath: /Users/kimsanghoon/IdeaProjects/uEngine5-uEngine6
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        bpm-in:
          group: bpm
          destination: bpm-topic
          contentType: application/json
        bpm-out:
          destination: bpm-topic
          contentType: application/json

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug

server:
  port: 9094

filter:
  payload:
    enabled: true

mail:
  enabled: true
  smtp:
    host: smtp.gmail.com
    port: 587
    auth: true
    starttls:
      enable: true
    ssl:
      trust: smtp.gmail.com
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}



---

spring:
  profiles: docker
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        bpm-topic:
          destination: bpm.topic
          contentType: application/json